name: Fetch Camera Snapshots

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Installing the requests library for API calls

      - name: Fetch and save snapshots
        run: |
          python fetch_snapshots.py  # Run the Python script to fetch snapshots
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Reference the secret here

      - name: Check if the snapshots directory exists
        run: |
          if [ ! -d "snapshots" ]; then
            mkdir snapshots  # Create the snapshots folder if it doesn't exist
          fi

      - name: Commit and push new snapshots
        run: |
          git config --local user.name "jmorr17"
          git config --local user.email "jmorris@lakecountyco.gov"
          
          # Set the GitHub remote URL using the token for authentication
          git remote set-url origin https://$GH_TOKEN@github.com/jmorr17/LC-Cameras.git
          
          git add snapshots/  # Add the new snapshots
          git commit -m "Update camera snapshots" || echo "No changes to commit"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub Token secret for authentication


