name: Upload Snapshots

on:
  push:
    paths:
      - 'snapshots/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jmorr17/LC-Cameras-Public.git

    - name: Commit and push new snapshots
      run: |
        git add snapshots/
        git commit -m "Update camera snapshots" || echo "No changes to commit"
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
