name: Upload Camera Snapshots

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour (adjust as necessary)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Download Snapshot
        run: |
          curl -H "Authorization: Bearer ${{ secrets.API_KEY }}" -o snapshot.jpg https://camera-portal.com/api/snapshot
          mkdir -p images
          mv snapshot.jpg images/snapshot_$(date +'%Y%m%d%H%M%S').jpg

      - name: Commit and push new snapshot
        run: |
          git config --local user.name "Your GitHub Username"
          git config --local user.email "your-email@example.com"
          git add .
          git commit -m "Add new camera snapshot"
          git push origin main
